### ISSUE TITLE
Issues installing with python 2.7 anaconda version

### ISSUE THREAD

**Issue by lwinte01** [rstoneback/pysatCDF#2]
Any chance this can be installed easily with anaconda?

I had issues trying to install following the README instructions (using MacOSX).

Here is the output:

swe16:pysatCDF lwinter$ python setup.py install
Unable to find CDF installation in default location.
Building CDF for pysatCDF.
running install
running bdist_egg
running egg_info
running build_src
Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'Programming Language :: Python :: 3.4',
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/install.py", line 62, in run
    r = self.setuptools_run()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/install.py", line 56, in setuptools_run
    self.do_egg_install()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/egg_info.py", line 18, in run
    self.run_command("build_src")
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 128, in finalize_options
    build_ext = self.get_finalized_command('build_ext')
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 75, in finalize_options
    self.set_undefined_options('build', ('parallel', 'parallel'))
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: parallel

**Comment by rstoneback** [comment]
Thanks for the note. I'll take a look.

Russell

On Sep 21, 2016, at 3:08 PM, Lisa Winter <notifications@github.com<mailto:notifications@github.com>> wrote:


Any chance this can be installed easily with anaconda?

I had issues trying to install following the README instructions (using MacOSX).

Here is the output:

swe16:pysatCDF lwinter$ python setup.py install
Unable to find CDF installation in default location.
Building CDF for pysatCDF.
running install
running bdist_egg
running egg_info
running build_src
Traceback (most recent call last):
File "setup.py", line 273, in
'Programming Language :: Python :: 3.4',
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
return old_setup(**new_attr)
File "/Users/lwinter/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/install.py", line 62, in run
r = self.setuptools_run()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/install.py", line 56, in setuptools_run
self.do_egg_install()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
self.run_command('bdist_egg')
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 152, in run
self.run_command("egg_info")
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/egg_info.py", line 18, in run
self.run_command("build_src")
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/Users/lwinter/anaconda/lib/python2.7/distutils/dist.py", line 971, in run_command
cmd_obj.ensure_finalized()
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
self.finalize_options()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 128, in finalize_options
build_ext = self.get_finalized_command('build_ext')
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
cmd_obj.ensure_finalized()
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
self.finalize_options()
File "/Users/lwinter/anaconda/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 75, in finalize_options
self.set_undefined_options('build', ('parallel', 'parallel'))
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
getattr(src_cmd_obj, src_option))
File "/Users/lwinter/anaconda/lib/python2.7/distutils/cmd.py", line 105, in getattr
raise AttributeError, attr
AttributeError: parallel

-

**Comment by rstoneback** [comment]
I've posted a new version that builds for me in an anaconda python installation. Please let me know if you run into any more issues.
